name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.9", "3.10"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    # - name: Save pytest cache
    #   id: save-pytest-cache
    #   uses: actions/cache@v4
    #   with:
    #     path: ~/.pytest_cache
    #     # key: ${{ runner.os }}-${{ matrix.python }}-pytest-cache
    #     key: pytest-cache
    - name: Run tests
      run: pytest -v --rank --rank-weight=1-0-0
    - name: Print pytest cache
      run: ls /home/runner/work/demo/demo/.pytest_cache/v/

    # - name: Print pytest-ranking cache
    #   if: steps.save-pytest-cache.outputs.cache-hit == 'true'
    #   run: cat ~/.pytest_cache/v/pytest_ranking_data/last_durations

    # - name: Cache Primes
    #   id: cache-primes
    #   uses: actions/cache@v4
    #   with:
    #     path: ~/sample.txt
    #     key: ${{ runner.os }}-primes
    #     save-always: true

    # - name: Pring Prime Numbers
    #   if: steps.cache-primes.outputs.cache-hit == 'true'
    #   run: cat ~/sample.txt

    # - name: Generate Prime Numbers
    #   # if: steps.cache-primes.outputs.cache-hit != 'true'
    #   run: echo 'apple' >> ~/sample.txt
