name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.9", "3.10"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    # - name: Setup pytest-ranking cache
    #   id: setup-pytest-ranking-cache
    #   uses: actions/cache@v4
    #   with:
    #     path: /.pytest_cache/v/pytest_ranking_data
    #     key: ${{ runner.os }}-${{ matrix.python }}-pytest-ranking-cache
    # - name: Run tests
    #   run: pytest -v --rank --rank-weight=1-0-0

    # - name: Generate sample.txt
    #   run: echo 'this is an apple' >> /sample.txt    
    # - name: Cache sample
    #   id: cache-sample
    #   uses: actions/cache@v4
    #   with:
    #     path: /sample.txt
    #     key: ${{ runner.os }}-${{ matrix.python }}-sample


    - name: Cache Primes
      id: cache-primes
      uses: actions/cache@v4
      with:
        path: prime-numbers
        key: ${{ runner.os }}-primes

    - name: Generate Prime Numbers
      # if: steps.cache-primes.outputs.cache-hit != 'true'
      run: echo 'apple' >> sample.txt
